<?php echo $this->doctype(); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->render('layout/head'); ?>
    </head>

    <body>

        <!-- Header -->
        <header class="header navbar navbar-fixed-top" role="banner">
            <?php echo $this->render('layout/header'); ?>
        </header> <!-- /.header -->

        <div id="container">
            <div id="sidebar" class="sidebar-fixed">
                <?php echo $this->render('layout/left-sidebar'); ?>
            </div>
            <!-- /Sidebar -->

            <div id="content">
                <div class="container">
                    <!-- Breadcrumbs line -->
                    <div class="crumbs">
                        <?php echo $this->render('layout/breadcrumbs'); ?>
                    </div>
                    <!-- /Breadcrumbs line -->

                    <!--=== Page Header ===-->
                    <div class="page-header">

                        <div class="page-title">
                            <h3>Dashboard</h3>
                            <span>Good morning, John!</span>
                        </div>

                        <!-- Page Stats -->
                        <ul class="page-stats">
                            <?php echo $this->render('layout/statistic'); ?>
                        </ul>
                        <!-- /Page Stats -->
                    </div>
                    <!-- /Page Header -->

                    <!--=== Page Content ===-->
                    <?php echo $this->content;?>
                    <?php //include_once("content/blank.phtml"); ?>
                    <!-- /Page Content -->
                </div>
                <!-- /.container -->
            </div>
        </div>

    </body>
</html>